# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tq < Formula
  desc "tq is a portable command-line JSON/YAML processor."
  homepage "https://github.com/jarxorg/tree#tq"
  version "0.8.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jarxorg/tree/releases/download/v0.8.2/tree_0.8.2_darwin_amd64.tar.gz"
      sha256 "47e9c34d0acfe71d01d9d4a4a3f4d201ca61aab4438c6595da45b745371d4aaa"

      def install
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jarxorg/tree/releases/download/v0.8.2/tree_0.8.2_darwin_arm64.tar.gz"
      sha256 "d393b2aad38fed7e02cd62ffea673da3e6911225e8c8864c43c3b38bbcc44f13"

      def install
        bin.install "tq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jarxorg/tree/releases/download/v0.8.2/tree_0.8.2_linux_amd64.tar.gz"
      sha256 "1f695a67b005a85a0603d8789fbcde8ae438026e0a8108c4ee479e6320454559"
      def install
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jarxorg/tree/releases/download/v0.8.2/tree_0.8.2_linux_arm64.tar.gz"
      sha256 "fb82c3090b06444748f4dc1c80ab7a2a39965e8231f777a361e4f01acbd3a990"
      def install
        bin.install "tq"
      end
    end
  end
end
