# This file was generated by GoReleaser. DO NOT EDIT.
cask "tq" do
  desc "tq is a portable command-line JSON/YAML processor."
  homepage "https://github.com/jarxorg/tree#tq"
  version "0.8.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tq"

  on_macos do
    on_intel do
      url "https://github.com/jarxorg/tree/releases/download/v0.8.1/tree_0.8.1_darwin_amd64.tar.gz"
      sha256 "c9be685296617369c1810e339c74e18ace632c5236d3e4ba390a073b6a820c54"
    end
    on_arm do
      url "https://github.com/jarxorg/tree/releases/download/v0.8.1/tree_0.8.1_darwin_arm64.tar.gz"
      sha256 "f77c0471ac3363c1709ba9aa6f733a84bb4218a2c2a30b304c53baff9be7edba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jarxorg/tree/releases/download/v0.8.1/tree_0.8.1_linux_amd64.tar.gz"
      sha256 "5fcb4ac13b93b4aa925bd2745b5ec4030b815da83a5e1b873f2f50eb9711e514"
    end
    on_arm do
      url "https://github.com/jarxorg/tree/releases/download/v0.8.1/tree_0.8.1_linux_arm64.tar.gz"
      sha256 "e08e6a45b17813995ac848297cee48265885b0888f5398bd6921577c8fa35471"
    end
  end

  # No zap stanza required
end
