# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tq < Formula
  desc "tq is a portable command-line JSON/YAML processor."
  homepage "https://github.com/jarxorg/tree#tq"
  version "0.5.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.7/tree_0.5.7_Darwin_arm64.tar.gz"
      sha256 "d8051e2c9ae38b03520ea633b18455f24ba816c26f6f72b60c2c8e848fe277e2"

      def install
        bin.install "tq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.7/tree_0.5.7_Darwin_x86_64.tar.gz"
      sha256 "a312d545b9db00009400769f88b43d5bb2c0e253ca72ac4bcce725118ed7c425"

      def install
        bin.install "tq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.7/tree_0.5.7_Linux_x86_64.tar.gz"
      sha256 "60be43f0f0b8b663676390bb582c982867bd1be2f509d4e6865ea76a5507ecee"

      def install
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.7/tree_0.5.7_Linux_arm64.tar.gz"
      sha256 "776ce19654c95a4a9d8c792804f9644ad33b1ac45ed3dfa5e4abd4539b1f3338"

      def install
        bin.install "tq"
      end
    end
  end

  test do
    system "#{bin}/tq --help"
  end
end
