# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tq < Formula
  desc "tq is a portable command-line JSON/YAML processor."
  homepage "https://github.com/jarxorg/tree#tq"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jarxorg/tree/releases/download/v0.7.1/tree_0.7.1_Darwin_x86_64.tar.gz"
      sha256 "892b89fc95a1319209c5aa0868c7c840221d781f6652b8104305bc3bccad62a0"

      def install
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jarxorg/tree/releases/download/v0.7.1/tree_0.7.1_Darwin_arm64.tar.gz"
      sha256 "fef75ebe557a2da0741ebff77586a16ccf9076f5e42249afa5b5456ffd1b7d58"

      def install
        bin.install "tq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jarxorg/tree/releases/download/v0.7.1/tree_0.7.1_Linux_x86_64.tar.gz"
      sha256 "c9c9478b2325931e8b835a89d542ffc8d8e5bd33c4042411f7bcacd9eb24ea83"

      def install
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jarxorg/tree/releases/download/v0.7.1/tree_0.7.1_Linux_arm64.tar.gz"
      sha256 "9876087cc2f3f71a0911a378aa2c37decb86ce3fd2d534a80e92c001d418ff22"

      def install
        bin.install "tq"
      end
    end
  end

  test do
    system "#{bin}/tq --help"
  end
end
