# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tq < Formula
  desc "tq is a portable command-line JSON/YAML processor."
  homepage "https://github.com/jarxorg/tree#tq"
  version "0.5.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.6/tree_0.5.6_Darwin_x86_64.tar.gz"
      sha256 "b135e9de89b6f7fd6aa282c5da6117af734a034194f51f19f7ddcdfcde4458c2"

      def install
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.6/tree_0.5.6_Darwin_arm64.tar.gz"
      sha256 "d8144ae44fdc0f3818008ef3d8c32c7060177deddf20d68d5ca6797e2c057406"

      def install
        bin.install "tq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.6/tree_0.5.6_Linux_x86_64.tar.gz"
      sha256 "0ff7e9b5e09f4ab26b752e60ae2ff8dee68cc7c76c154c47bc241e10816b4f5e"

      def install
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.6/tree_0.5.6_Linux_arm64.tar.gz"
      sha256 "0da3f5c1c2bc309134f32353e5c1c8af437ed936fc0081ef232364663853cac8"

      def install
        bin.install "tq"
      end
    end
  end

  test do
    system "#{bin}/tq --help"
  end
end
