# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tree < Formula
  desc ""
  homepage "https://github.com/jarxorg/tree#tq"
  version "0.5.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.4/tree_0.5.4_Darwin_x86_64.tar.gz"
      sha256 "44c2ecfc78729fde65e5e31b910da56c8fd2519129586c2cb6c653a6cda7cf9a"

      def install
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.4/tree_0.5.4_Darwin_arm64.tar.gz"
      sha256 "172532d470ae1b970541c73487a24678ace614c1b7393acf3e91248ec18adfed"

      def install
        bin.install "tq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.4/tree_0.5.4_Linux_x86_64.tar.gz"
      sha256 "b37226b7dea8abf76119196e856f7f73c29262a8c8e9155a725efbec4fd193a5"

      def install
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jarxorg/tree/releases/download/v0.5.4/tree_0.5.4_Linux_arm64.tar.gz"
      sha256 "67441dd95f67d07ea59f70c7f3899a96c2d90c95193c0a1cbe4a3c7c656d85cf"

      def install
        bin.install "tq"
      end
    end
  end

  test do
    system "#{bin}/tq --help"
  end
end
